platform :ios, "7.0"
pod 'CHTCollectionViewWaterfallLayout',		'~> 0.7'
pod 'MBProgressHUD',				'~> 0.8'
pod 'AFNetworking',              		'~> 2.0'
pod 'AFNetworking/NSURLSession',		'~> 2.0'
pod 'Reachability',				'~> 3.1.1'
pod 'URBMediaFocusViewController'
pod 'PSTCollectionView',			'~> 1.2'
pod 'DACircularProgress',			'~> 2.2'
pod 'NSData+Base64',				'~> 1.0'
pod 'UIImage-Resize',				'~> 1.0'
